application: industrial-gist-87021
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.3"

builtins:
- django_wsgi: on

handlers:
- url: .*
  script: main.app
